CONT EQU 10H
COMP EQU 11H
EOI EQU 20H
IMR EQU 21H
INT0 EQU 24H
INT1 EQU 25H
INT2 EQU 26H
PA EQU 30H
PB EQU 31H
CA EQU 32H
CB EQU 33H
DATO EQU 40H
ESTADO EQU 41H
IDF10 EQU 1
IDTIMER EQU 2
IDHAND EQU 3

ORG 1000h
MSJ DB "Ingrese un numero del 1 al 9"
FIN DB ?
NUM DB ?

ORG 3000h

leer_digito: MOV BX, offset msj
  MOV AL, offset fin - offset msj
  INT 7
  loop: MOV BX, OFFSET NUM
  MOV AL, 1
  INT 6
  CMP NUM, 030h
  JZ LOOP
  CMP NUM, 03Ah
  JNS LOOP
  MOV CL, NUM
  RET

poll: IN AL, ESTADO
  AND AL, 1
  JNZ poll
  RET

descender: MOV BX, SP
  ADD BX, 4 
loop2: call poll
  MOV AL, [BX]
  OUT DATO, AL
  CMP AL, 30h
  JZ fin2
  DEC byte ptr [BX]
  JMP loop2
  IRET
  
 ORG 2000H
  ; ASIGNO LA DIRECCION DE LA SUBRUTINA A EJECUTAR EN EL VECTOR DE INTERRUPCIONES PARA MI IDF10
  MOV BX, IDF10 * 4
  MOV AX, descender
  MOV [BX], AX
  ; Libero el registro completo de AX (todo en 0)
  XOR AX, AX
  ; CONFIGURO EL HS MODO POLLING
  IN AL, ESTADO
  AND AL, 01111111b
  OUT ESTADO, AL
  CLI ; CONFIGURO EL PIC PARA INTERRUPCION F10
  ; ACTIVO EL DISP F10 (IMR)
  MOV AL, 11111110b
  OUT IMR, AL
  ; PONGO EL ID DE LA TECLA F10 EN INT0
  MOV AL, IDF10
  OUT INT0, AL
  STI
  CALL LEER_DIGITO
  PUSH CX
asd: JMP asd
fin2: HLT
END
